export const GROCERY_CATEGORIES = [
  "Produce",
  "Dairy",
  "Meat & Seafood",
  "Bakery",
  "Pantry & Dry Goods",
  "Frozen",
  "Beverages",
  "Condiments & Sauces",
  "Snacks",
  "Other",
] as const;

export type GroceryCategory = (typeof GROCERY_CATEGORIES)[number];

const CATEGORY_KEYWORDS: Record<GroceryCategory, string[]> = {
  Produce: [
    "apple",
    "banana",
    "onion",
    "garlic",
    "tomato",
    "lettuce",
    "carrot",
    "celery",
    "pepper",
    "mushroom",
    "potato",
    "broccoli",
    "spinach",
    "kale",
    "cucumber",
    "zucchini",
    "avocado",
    "lemon",
    "lime",
    "ginger",
    "cilantro",
    "parsley",
    "basil",
    "mint",
    "scallion",
    "shallot",
    "berry",
    "strawberr",
    "blueberr",
    "raspberr",
    "mango",
    "pineapple",
    "orange",
    "peach",
    "pear",
    "grape",
    "melon",
    "corn",
    "cabbage",
    "cauliflower",
    "beet",
    "radish",
    "asparagus",
    "artichoke",
    "squash",
    "sweet potato",
    "green bean",
    "pea",
    "jalapeno",
    "serrano",
    "habanero",
    "chili",
    "chile",
    "arugula",
    "romaine",
    "chard",
    "collard",
    "dill",
    "rosemary",
    "thyme",
    "sage",
    "chive",
    "leek",
    "fennel",
    "turnip",
    "eggplant",
  ],
  Dairy: [
    "milk",
    "cream",
    "cheese",
    "butter",
    "yogurt",
    "egg",
    "eggs",
    "ricotta",
    "mozzarella",
    "parmesan",
    "cheddar",
    "feta",
    "sour cream",
    "cream cheese",
    "half and half",
    "half-and-half",
    "whipping cream",
    "heavy cream",
    "cottage cheese",
    "gouda",
    "gruyere",
    "brie",
    "goat cheese",
    "mascarpone",
  ],
  "Meat & Seafood": [
    "chicken",
    "beef",
    "pork",
    "lamb",
    "turkey",
    "sausage",
    "bacon",
    "ham",
    "steak",
    "ground",
    "salmon",
    "shrimp",
    "tuna",
    "cod",
    "prosciutto",
    "pancetta",
    "chorizo",
    "meatball",
    "brisket",
    "rib",
    "tenderloin",
    "thigh",
    "breast",
    "wing",
    "drumstick",
    "crab",
    "lobster",
    "scallop",
    "mussel",
    "clam",
    "oyster",
    "anchov",
    "tilapia",
    "halibut",
    "mahi",
    "trout",
    "catfish",
  ],
  Bakery: [
    "bread",
    "bun",
    "roll",
    "tortilla",
    "pita",
    "naan",
    "baguette",
    "croissant",
    "bagel",
    "english muffin",
    "flatbread",
    "ciabatta",
    "sourdough",
    "brioche",
  ],
  "Pantry & Dry Goods": [
    "flour",
    "sugar",
    "rice",
    "pasta",
    "noodle",
    "oat",
    "quinoa",
    "lentil",
    "canned",
    "broth",
    "stock",
    "olive oil",
    "vegetable oil",
    "canola oil",
    "sesame oil",
    "coconut oil",
    "vinegar",
    "baking",
    "cornstarch",
    "salt",
    "pepper",
    "cumin",
    "paprika",
    "cinnamon",
    "oregano",
    "vanilla",
    "honey",
    "maple syrup",
    "molasses",
    "spaghetti",
    "penne",
    "fusilli",
    "linguine",
    "fettuccine",
    "macaroni",
    "couscous",
    "barley",
    "bean",
    "chickpea",
    "black bean",
    "kidney bean",
    "pinto bean",
    "nut",
    "almond",
    "walnut",
    "pecan",
    "cashew",
    "peanut",
    "pine nut",
    "sesame",
    "breadcrumb",
    "panko",
    "cocoa",
    "chocolate",
    "baking powder",
    "baking soda",
    "yeast",
    "corn meal",
    "cornmeal",
    "coconut milk",
    "tomato paste",
    "tomato sauce",
    "diced tomato",
    "crushed tomato",
  ],
  Frozen: ["frozen", "ice cream"],
  Beverages: [
    "juice",
    "water",
    "soda",
    "coffee",
    "tea",
    "wine",
    "beer",
    "sparkling",
    "kombucha",
    "lemonade",
  ],
  "Condiments & Sauces": [
    "ketchup",
    "mustard",
    "mayo",
    "mayonnaise",
    "hot sauce",
    "soy sauce",
    "sriracha",
    "salsa",
    "pesto",
    "tahini",
    "hoisin",
    "fish sauce",
    "worcestershire",
    "bbq sauce",
    "barbecue sauce",
    "teriyaki",
    "oyster sauce",
    "chili sauce",
    "sambal",
    "gochujang",
    "miso",
    "curry paste",
    "harissa",
    "chimichurri",
    "ranch",
    "relish",
  ],
  Snacks: [
    "chip",
    "cracker",
    "pretzel",
    "popcorn",
    "granola",
    "trail mix",
    "dried fruit",
    "jerky",
  ],
  Other: [],
};

export function categorizeItem(name: string): GroceryCategory {
  const lower = name.toLowerCase().trim();
  for (const [category, keywords] of Object.entries(CATEGORY_KEYWORDS)) {
    if (category === "Other") continue;
    for (const keyword of keywords) {
      if (lower.includes(keyword)) {
        return category as GroceryCategory;
      }
    }
  }
  return "Other";
}
